### ISSUE TITLE
Conflict with Crocoblocks JetEngine

### ISSUE THREAD

**Issue by zanga7** [analogwp/analogwp-templates#413] opened 2020-09-01 13:19 UTC
I cannot edit Elementor pages within 'Listings' within JetEngine. Spinning circle.
Does not effect editing of other pages.

**Comment by gvgvgvijayan** [comment] 2020-09-01 13:21
Hello @zanga7,

Thanks for reaching us.
 which version of style kit you are using?

**Comment by zanga7** [comment] 2020-09-01 13:28
Free 1.7.1

**Comment by gvgvgvijayan** [comment] 2020-09-01 13:30
Thanks for the input.
Could you please share the screenshot of the page which causes the issue?

**Comment by zanga7** [comment] 2020-09-01 13:33
<img width="450" alt="Screenshot at Sep 01 23-32-42" src="https://user-images.githubusercontent.com/70584779/91857634-7bdf0e80-ecab-11ea-9363-e2aed605be4d.png">
<img width="569" alt="Screenshot at Sep 01 23-32-09" src="https://user-images.githubusercontent.com/70584779/91857642-7f729580-ecab-11ea-8b5c-ad7bd8bac0e9.png">

**Comment by gvgvgvijayan** [comment] 2020-09-01 13:34
Could you please share the JS console log.

**Comment by zanga7** [comment] 2020-09-01 13:35
**This???**

she-header.js:42 -1
ang-action.min.js:1 Uncaught TypeError: Cannot read property 'addTab' of undefined
    at Editor.<anonymous> (ang-action.min.js:1)
    at p (backbone.min.js:2)
    at f (backbone.min.js:2)
    at l (backbone.min.js:2)
    at Editor.n.trigger (backbone.min.js:2)
    at Editor.onPreviewLoaded (editor.min.js:2)
    at Editor.onPreviewLoaded (editor.min.js:2)
    at HTMLIFrameElement.dispatch (load-scripts.php:3)
    at HTMLIFrameElement.r.handle (load-scripts.php:3)
DevTools failed to load SourceMap: Could not load content for http://mydomain.com/wp-content/plugins/elementor/assets/lib/pickr/pickr.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Comment by gvgvgvijayan** [comment] 2020-09-01 13:39
Yes

**Comment by gvgvgvijayan** [comment] 2020-09-01 13:47
Could you please share the file path of `she-header.js` or if you know from which plugin it's loading please share that plugin name or link.

**Comment by zanga7** [comment] 2020-09-01 13:50
Seems to be 'Sticky Headers for Elementor' 
http://template.mezzanine.net.au/wp-content/plugins/sticky-header-effects-for-elementor/assets/js/she-header.js?ver=1.3.2

**Comment by zanga7** [comment] 2020-09-01 13:51
If I deactivate that plugin... i still get the error without that line.

DevTools failed to load SourceMap: Could not load content for http://template.mezzanine.net.au/wp-content/plugins/elementor/assets/lib/pickr/pickr.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
ang-action.min.js?ver=1598923964:1 Uncaught TypeError: Cannot read property 'addTab' of undefined
    at Editor.<anonymous> (ang-action.min.js?ver=1598923964:1)
    at p (backbone.min.js?ver=1.4.0:2)
    at f (backbone.min.js?ver=1.4.0:2)
    at l (backbone.min.js?ver=1.4.0:2)
    at Editor.n.trigger (backbone.min.js?ver=1.4.0:2)
    at Editor.onPreviewLoaded (editor.min.js?ver=3.0.5:2)
    at Editor.onPreviewLoaded (editor.min.js?ver=3.0.5:2)
    at HTMLIFrameElement.dispatch (load-scripts.php?c=0&load[chunk_0]=jquery&ver=5.5:3)
    at HTMLIFrameElement.r.handle (load-scripts.php?c=0&load[chunk_0]=jquery&ver=5.5:3)

**Comment by gvgvgvijayan** [comment] 2020-09-01 13:57
Could you please add us as admin in your site and share the credential detail (not here) by submitting: https://analogwp.com/support/ so that we can inspect and find the issue.

**Comment by zanga7** [comment] 2020-09-01 14:01
Done

**Comment by gvgvgvijayan** [comment] 2020-09-01 14:16
Hi @zanga7,

Could you please check your site and share your thoughts regarding still you are facing the issue or not.

**Comment by zanga7** [comment] 2020-09-01 14:18
Yes, still facing the issue. If you see 'JetEngine' and go to edit page under 'Listings' this is where I am getting the spinning wheel.

**Comment by zanga7** [comment] 2020-09-01 14:39
My laptop is just about to go flat and I don't have a charger. I'll jump back on in the morning when I'm back in the office. Thanks for the support on this 👍 I'd better upgrade to pro now 😉

**Comment by gvgvgvijayan** [comment] 2020-09-01 14:44
It's a bug.

The plugin `JetEngine` (https://crocoblock.com/plugins/jetengine/) is from a closed source vendor so we will contact them to get a plugin.

Here sharing the insight that we found is, the page `test` generated using `JetEngine` is not a default page it's a Custom Post Type (CPT) page when we editing this CPT page only throws the JS error.

If we edit any default page of post type `page` the JS error is not throwing in the console. Therefore we found the root cause we will fix it.

**Comment by gvgvgvijayan** [comment] 2020-09-02 07:23
Tried with sample custom post type to check is the error reproduced but it's not. The next step will be we will contact `JetEngine` team.
![cpt_el_editor](https://user-images.githubusercontent.com/4319097/91944100-2b9f9500-ed1b-11ea-82c4-8dd02cc0a52a.png)
![cpt_admin_page](https://user-images.githubusercontent.com/4319097/91944105-2e01ef00-ed1b-11ea-8127-442455394b9d.png)

**Comment by gvgvgvijayan** [comment] 2020-09-02 07:56
Hi @zanga7,

We raised a ticket (ID: 16972) in crocoblock support forum.

Authenticated link: https://support.crocoblock.com/support/tickets/16972

**Comment by zanga7** [comment] 2020-09-02 08:03
The issue is not in custom post type... its in the 'Listings' in JetEngine. 
You're welcome to poke about the site I gave you access to.

**Comment by gvgvgvijayan** [comment] 2020-09-02 09:05
The admin page shown in the `Listings` menu is a custom post type. The CPT name is `jet-engine` for details please see the highlight in the attached image
![Screenshot from 2020-09-02 14-23-38](https://user-images.githubusercontent.com/4319097/91960993-344a9800-ed28-11ea-8039-a7f649f3c3f8.png)

We wrote a script in theme `functions.php` (revoke to original once we checked) to check the rendering page's post type that also denotes `jet-engine`
![Screenshot from 2020-09-02 14-16-53](https://user-images.githubusercontent.com/4319097/91961551-f0a45e00-ed28-11ea-9eb7-814de97883f8.png)

Here is the snippet we used to detect the post type in the front end:
```
add_action(
	'template_redirect',
	function() {

		$post_id   = get_queried_object_id();
		$post_type = get_post_type( $post_id );

		if ( 133 === $post_id ) {
			var_dump( $post_type );
		}
	}
);
```

**Comment by gvgvgvijayan** [comment] 2020-09-02 15:43
Hi @zanga7,

We got the reply to the ticket: https://support.crocoblock.com/support/tickets/16972

Crocoblock reply: 

> Unfortunately we cannot provide JetEngine plugin for free. But you may test our plugin directly from customer's WordPress panel.

Our reply:

> Understood due to company policy we won't get the plugin JetEngine for free.

Could you please provide us test environment to do further proceedings. As there we will do debugging we worried not to show any debugging data to end-users therefore please provide a clone of the issue causing server.

**Comment by JohnPixle** [comment] 2020-09-02 15:45
@gvgvgvijayan I already have a license with Jet Engine plugin for debugging purposes, it is in our testing site, I just activated it. Ping me if you need any help :)

**Comment by gvgvgvijayan** [comment] 2020-09-02 15:53
@JohnPixle Thanks.

@zanga7 we will check in our environment. If we need any information we will let you know.

> @gvgvgvijayan I already have a license with Jet Engine plugin for debugging purposes, it is in our testing site, I just activated it. Ping me if you need any help :)

**Comment by gvgvgvijayan** [comment] 2020-09-03 08:18
Hi @zanga7,

### Progress status:

We suspect that the reason for the issue is two menus `Site Settings` & `Theme Builder` was removed when visiting the CPT `jet-engine` pages.

Our plugin `Style Kit` relies on the `Site Settings` panel of Elementor editor but it's removed in the CPT `jet-engine` pages. As a result of that, the error is thrown.

We will do further analysis to find precisely where the `Site Settings` menu item was removed.

### Please find the difference by comparing these two images:

**`jet-engine` post type editor panel:**
![jet_enging_custom_post_type](https://user-images.githubusercontent.com/4319097/92089458-ce274900-edeb-11ea-8c1d-bf769b399e28.png)

**Other post type editor panel:**
![other_custom_post_type](https://user-images.githubusercontent.com/4319097/92089535-e72ffa00-edeb-11ea-84d4-5b8539c6cd16.png)

**Comment by gvgvgvijayan** [comment] 2020-09-07 07:28
Hi @zanga7,

Crocoblock requested to share the credential of the site. Could you please provide one more temporary credential for Crocoblock through https://analogwp.com/support/.

Here is the last conversation that happened between us and Crocoblock:
**Crocoblock reply:**
Take our apologies for a long delay!

In order for us to investigate this particular case we need access to your WordPress admin panel. Could you please provide us with the login credentials and its url.
Thank you.

**Our reply:**
You can reproduce the same in any environment. The thing required is both JetEngine plugin and https://wordpress.org/plugins/analogwp-templates/ need to be installed.

Once both plugins activated, go to JetEngine->listings page.

Edit anyone posts of "Listing Items" by clicking the action link "Edit with Elementor".

In Elementor editor page the side panel loading icon is showing persistently, if you inspect using a web developer tool you will get this error:

Uncaught TypeError: Cannot read property 'addTab' of undefined
    at Editor.<anonymous> (ang-action.min.js?ver=1599460124:1)
    at p (backbone.min.js?ver=1.4.0:2)
    at f (backbone.min.js?ver=1.4.0:2)
    at l (backbone.min.js?ver=1.4.0:2)
    at Editor.n.trigger (backbone.min.js?ver=1.4.0:2)
    at Editor.onPreviewLoaded (editor.min.js?ver=3.0.5:2)
    at Editor.onPreviewLoaded (editor.min.js?ver=3.0.5:2)
    at HTMLIFrameElement.dispatch (load-scripts.php?c=0&load[chunk_0]=jquery-core&ver=5.5.1:3)
    at HTMLIFrameElement.r.handle (load-scripts.php?c=0&load[chunk_0]=jquery-core&ver=5.5.1:3)

The root cause of the error is the "Site Settings" control is missing which is by default come with the Elementor.

Apart from this, I will request the client to share a temporary credential for you in their server.

**Comment by gvgvgvijayan** [comment] 2020-09-07 14:11
Hi @zanga7,

Is it ok for you to provide a timely update that we get from the `Crocoblock dev team` or else we can provide a final update but we worried to provide you exactly when you will get as this conversation depends on the `JetEnfine team` too? Or even better without tagging you, we can add what are the conversations that happened between us (AnalogWP & JetEngine team) you can visit this issue to get the status also at any time you can tag me if you need any clarification/reply.

**Crocoblock reply:**
We have checked from our end and as you can see from the screenshot the issue is with Analog Templates plugin https://prnt.sc/ucw9ju
Unfortunately we do not provide support for third party plugins.

**AnalogWP reply:**
Could you please share the version of Elementor and Style Kits for Elementor by visiting the plugins list page.

**Crocoblock reply:**
The version of Elementor is 2.9.11 and Style Kit is 1.7.1

**AnalogWP reply:**
Please update the Elementor to version 3. 

The customer who facing the issue is with the following version in the environment 
Elementor - 3.0.5
Elementor Pro - 3.0.2
JetEngine - 2.4.11
Style Kits for Elementor - 1.7.1

**Comment by zanga7** [comment] 2020-09-07 23:26
@gvgvgvijayan 
Thanks for the updates. This fix is VERY important to us.
I don't quite understand what's happening but trust you're working hard to find a solution.

**Comment by gvgvgvijayan** [comment] 2020-09-08 06:03
@zanga7,

We understand your situation how strongly depend on both `AnalogWP Style Kits` and `Crocoblock JetEngine` plugins.

The issue is Elementor default menus `Site Settings` and `Theme Builder` are missing in CPT `jet-engine` pages as explained in the comment: https://github.com/analogwp/analogwp-templates/issues/413#issuecomment-686333377

Therefore we conveyed these missing menus to Crocoblock and awaiting their response.

**Comment by zanga7** [comment] 2020-09-10 04:48
@gvgvgvijayan Any updates? I need to wrap up a project and this is blocking me. :-(

**Comment by gvgvgvijayan** [comment] 2020-09-10 06:24
@zanga7,

We are waiting for the `Crocoblock` support team reply for 3 days. I'm daily requesting them to share the update but no reply from `Crocoblock`.

If it's urgent we will replicate the code changes which we committed in this issue in your server style kit plugin file too. 
(We did check whether the `Global` panel is available or not. Here are the changes we did: https://github.com/analogwp/analogwp-templates/pull/414/files)

`Crocoblock` needs to confirm why the default `Elementor` menu `Site Settings` was removed which is responsible for the `Global` panel in the `JetEngine` `Listing` pages.
If you edit the `Listing` pages in the Elementor editor, the `Site Settings` menu removed therefore you can't use style kits in the `Listing` pages.

**Comment by zanga7** [comment] 2020-09-10 06:44
I've deactivated SK. 
When I go to add a 'Listing' it pops up with this... 
![image](https://user-images.githubusercontent.com/70584779/92689552-8754c880-f382-11ea-9322-98879dbfb076.png)
I have to fill this out first... then everything seems to start working.
Activate stylekits and everything breaks again.

**Comment by gvgvgvijayan** [comment] 2020-09-10 06:51
@zanga7,

We will do the hotfix in the site http://template.mezzanine.net.au/

**Comment by gvgvgvijayan** [comment] 2020-09-10 09:12
@zanga7,

Please find the build:
https://github.com/gvgvgvijayan/block_storage/raw/master/analogwp-templates.zip

This build has [PR 414](https://github.com/analogwp/analogwp-templates/pull/414/files) code changes this will fix the issue JS error throwing in `Listing items` Elementor editor page.

**Closed** 2020-09-18 11:50 UTC
Labels: Type: Bug, status/has_pr
